# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"
gem "sinatra", "2.2.0"
gem "mysql2", "0.5.2"
gem "webrick", "1.7.0"
gem "json"
gem "sinatra-contrib", "2.2.0"